# This workflow will upload coverage files to codecov and codeclimate.

name: Coverage Report

on:
  release: 
    types:  [created]
  push:
     branches:
       - master

jobs:
  prepare:
    name: Create coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm testCov
      - run: zip coverageReport.zip coverage
      - uses: actions/upload-artifact@v1
        with:
          name: coverageReportFile
          path: coverage.zip
  
  codecov:
    name: Upload report to codecov
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/download-artifact@v1
        with:
          name: coverageReportFile
      - run: unzip coverage.zip -D coverage
      - run: npx codecov
  
  codeclimate:
    name: Upload report to codeclimate (re-test is needed)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: paambaati/codeclimate@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ codeclimate_id }}
        with:
            coverageCommand: npm run testCov
            debug: true
            
  